version: "3.8"

services:
  fastapi-app:
    build:
      context: .
    expose:
      - "8000"
    environment:
      - PORT=8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    volumes:
      - /etc/letsencrypt/live/gpt.lavapro.xyz/fullchain.pem:/etc/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/gpt.lavapro.xyz/privkey.pem:/etc/ssl/privkey.pem:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - fastapi-app
