version: '3.8'

services:
  fastapi-grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Add any environment variables you may need
      - PORT=8000
    restart: always
